openapi: 3.0.0
info:
  title: Image Upload API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /images:
    post:
      summary: Upload a new image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image uploaded successfully
    get:
      summary: Get a list of images
      responses:
        '200':
          description: A list of images
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: uri
                        name:
                          type: string
